print("(a) x = x + 1 -> x += 1 ")
print("(b) x = x / 2 -> x /= 2 ")
print("(c) x = x - 1 -> x -= 1")
print("(d) x = x + y -> x += y")
print("(e) x = x - (y + 7) -> x -= (y + 7)")
print("g: number_of_closed_cases = number_of_closed_cases + 2*ncc -> number_of_closed_cases += 2*ncc")
